version: '2'
services:
  pg-0:
    image: consdata/bitnami-postgresql-repmgr:13-witness-v2
    ports:
      - 5432:5432
    volumes:
      - pg_0_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_WITNESS_NODE=pg-witness
      - REPMGR_WITNESS_PORT=5432
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
      - REPMGR_PORT_NUMBER=5432
      - BITNAMI_DEBUG=true
      - REPMGR_LOG_LEVEL=DEBUG
  pg-1:
    image: consdata/bitnami-postgresql-repmgr:13-witness-v2
    ports:
      - 5433:5432
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_WITNESS_NODE=pg-witness
      - REPMGR_WITNESS_PORT=5432
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
      - REPMGR_PORT_NUMBER=5432
      - BITNAMI_DEBUG=true
      - REPMGR_LOG_LEVEL=DEBUG
  pg-2:
    image: consdata/bitnami-postgresql-repmgr:13-witness-v2
    ports:
      - 5434:5432
    volumes:
      - pg_2_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_WITNESS_NODE=pg-witness
      - REPMGR_WITNESS_PORT=5432
      - REPMGR_NODE_NAME=pg-2
      - REPMGR_NODE_NETWORK_NAME=pg-2
      - REPMGR_PORT_NUMBER=5432
      - BITNAMI_DEBUG=true
      - REPMGR_LOG_LEVEL=DEBUG
  pg-3:
    image: consdata/bitnami-postgresql-repmgr:13-witness-v2
    ports:
      - 5435:5432
    volumes:
      - pg_3_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_WITNESS_NODE=pg-witness
      - REPMGR_WITNESS_PORT=5432
      - REPMGR_NODE_NAME=pg-3
      - REPMGR_NODE_NETWORK_NAME=pg-3
      - REPMGR_PORT_NUMBER=5432
      - BITNAMI_DEBUG=true
      - REPMGR_LOG_LEVEL=DEBUG
  pg-witness:
    image: consdata/bitnami-postgresql-repmgr:13-witness-v2
    ports:
      - 5439:5432
    volumes:
      - pg_witness_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_NODE_NAME=pg-witness-9
      - REPMGR_NODE_NETWORK_NAME=pg-witness
      - REPMGR_PORT_NUMBER=5432
      - REPMGR_NODE_TYPE=witness
      - BITNAMI_DEBUG=true
      - REPMGR_LOG_LEVEL=DEBUG
volumes:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local
  pg_2_data:
    driver: local
  pg_3_data:
    driver: local
  pg_witness_data:
    driver: local
